---
swagger: "2.0"
info:
  description: This is the iRODS Query API
  version: 1.0.0
  title: iRODS Query API
  contact:
    email: info@irods.org
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
host: virtserver.swaggerhub.com
basePath: /jasoncoposky/irods-rest/1.0.0
tags:
- name: query
  description: general query endpoint
schemes:
- https
paths:
  /query:
    get:
      tags:
      - query
      summary: searches iRODS Catalog using the General Query Language
      description: |
        By passing in the appropriate options, you can search for
        anything within the iRODS Catalog
      operationId: catalogQuery
      produces:
      - application/json
      parameters:
      - name: query_string
        in: query
        description: pass a query string using the general query language or a query type
        required: true
        type: string
      - name: query_limit
        in: query
        description: maximum number of records to return
        required: false
        type: integer
        maximum: 50
        minimum: 0
        format: string
      - name: row_offset
        in: query
        description: number of records to skip for pagination
        required: false
        type: integer
        minimum: 0
        format: string
      - name: query_type
        in: query
        description: string description of the query type "general" or "specific"
        required: true
        type: string

      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/query_results'
        400:
          description: bad input parameter
definitions:
  query_results:
    type: object
    required:
    - results
    properties:
      results:
        type: string
        example: { "results" : [ [], [] ] }
